#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times.

i=1
while [ $i -lt 11 ]
do
    if [ $i = 9 ];then
        echo "hi"
    else
        echo "Best School"
    fi
    ((i++))
done
